### ISSUE TITLE
Include ide posts in RSS feed

### ISSUE THREAD

**Issue by davlse** [mpickering/blog#4]
Hello,

I noticed that the ide posts wasn't included in the atom feed.
It would be nice if they were or had a feed of their own.

Thanks

**Comment by k4rtik** [comment]
Ditto, I came searching both the the HTML repo and then to this one to find a feed.

**Comment by mpickering** [comment]
I can easily add a feed, but a PR which added the feed would be merged quickly. Everything is already set up to add it.

**Comment by mpickering** [comment]
There is now a link to an atom feed at the bottom of the IDE minisite. Please make a PR to fix if it doesn't work for you!

**Comment by k4rtik** [comment]
It works now, thanks! I haven't used Hakyll before or I would have certainly sent a PR (I once improved the RSS functionality for the popular Hugo site generator). I appreciate you adding the feed.

**Comment by k4rtik** [comment]
Hi, I see that the feed is generated and my feed reader correctly pulls in the content but the URL associated with each post is a little malformed; see, for example:
```
<id>
http://mpickering.github.io/ide/ide/posts/2020-05-15-multiple-components.html
</id>
```
(at https://mpickering.github.io/ide/atom.xml) which results in 404 if one wants to visit the page.

I can guess that the change needs to be either at line 165 or 202 at https://github.com/mpickering/blog/blob/master/site.hs but I am unsure.

**Comment by mpickering** [comment]
@k4rtik I pushed a fix now. Please open new issues if there are any more problems with the feed.
